- scripts/test_node_deploy.sh
Created bash file for running chain, also creates account, validator.
Add flag "--install" for reinstalling binary
> bash scripts for running chain, set up wallet, validator

- .github/workflows/sims.yml
- .github/workflows/test.yml
Tests still take too long, so more horsepower.
---
I have...
I have...
> 16 vcpu on long tests

- testutil/network/network.go
- x/pylons/client/cli/loud_game_test.go
Using Async Broadcast mode to reducing test time.
This PR close a part of #625. It reduce TestLOUDBasic from 400s to 200s
---
I have...
I have...
> Using async for reduce time test

- big-dipper/imports/api/admin.js
firebase library requires that the config is imported as an object thus placing the configs in settings file is not possible , however as suggested I have updated location of firebase.json to base folder Big-Dipper
Closes: #XXXX
---
I have...
I have...
> firebase.json is now placed with other config files in Big-Dipper Folder

- big-dipper/client/styles.scss
Fixed line height issue on big dipper
---
I have...
I have...
> line height was updated

- .github/workflows/sims.yml
- .github/workflows/test.yml
This PR replaces buildjet with Github actions because buildjet made only a small performance increase and only when running the entire test suite found in the 46 branch.
---
I have...
I have...
> remove buildjet

- big-dipper/imports/api/analytics/server/methods.js
- big-dipper/imports/api/notifications/server/methods.js
Push notification issue was fixed
---
I have...
I have...
> push notification key was updated

- big-dipper/imports/api/fcmtoken/server/methods.js
- big-dipper/imports/api/notifications/server/methods.js
Closes: #XXXX
---
I have...
I have...
> fixed multiple validation issues in endpoints

- .gitignore
- buf.gen.yaml
- proto/buf.lock
code generation for flutter is now supported
Closes: #XXXX
---
I have...
I have...
> dart code generation & some fixes

- buf.gen.yaml
dart grpc buf issue was fixed
---
I have...
I have...
> fix: dart grpc buf was fixed

- big-dipper/imports/api/blocks/server/methods.js
- big-dipper/imports/api/chain/server/methods.js
- big-dipper/package-lock.json
- big-dipper/yarn.lock
Closes: #XXXX
BigDipper URLs were update
---
I have...
I have...
> fix: url were update with cosmos sdk 0.46.0

- x/pylons/client/cli/tx_account.go
- x/pylons/keeper/msg_server_account.go
Closes: #XXXX
Fix: AppCheck was disabled for CLI use
---
I have...
I have...
> fix: app check was diabled for cli use

- big-dipper/imports/ui/easel_buy/EaselBuy.jsx
Closes: #XXXX
---
I have...
I have...
> updated big dipper get recipe history URL

- cmd/pylonsd/cmd/dev.go
- cmd/pylonsd/cmd/dev_validate_test.go
- cmd/pylonsd/cmd/gadgets.go
- cmd/pylonsd/cmd/gadgets_test.go
This pull request integrates the gadget system w/ the existing devtool integration tests. It also fixes a couple of minor oversights that kept those from passing, so it's a good thing we did this!
I have...
I have...
> Implement gadgets in integration tests, fix oversights

- app/upgrade/fork.go
- x/pylons/keeper/migrate.go
- x/pylons/module.go
- Fix migration bug.
---
I have...
I have...
> migrate fix

- .golangci.yml
- app/app.go
- app/upgrade/fork.go
- Upgrade handler for ibc
- IBC host
---
I have...
I have...
> Ibc upgrade fix and ibc host

- app/app.go
- app/upgrade/fork.go
- x/pylons/keeper/migrate.go
- x/pylons/module.go
- I fixed `fork.go` for ibc-host. It must run `RunMigrations` after `icamodule.InitModule`
---
I have...
I have...
> update fork for ibc-host

- app/app.go
- I forgot to add ICA to `ModuleBasics`. This PR to add it.
---
I have...
I have...
> minor:add ica to app module basic

- go.mod
- go.sum
ibc-go v5 was added to the ibc-go repo today.
This removes the replace statement that referenced the development branch. 
---
I have...
I have...
> use ibcv5 from mainline repo

- CHANGELOG.md
> add change log

- app/app.go
- cmd/pylonsd/cmd/root.go
Closes: #XXXX
So the upgrade flag makes upgrade via gov not working, we need to remove it for the upgrade since we're now switch to using gov for upgrade
---
I have...
I have...
> remove upgrade flag

- big-dipper/imports/api/api.js
- big-dipper/imports/api/codec.js
- big-dipper/imports/api/fcmtoken/fcmtoken.js
- big-dipper/imports/api/fcmtoken/server/methods.js
- big-dipper/imports/api/notifications/notifications.js
- big-dipper/imports/api/notifications/server/methods.js
- big-dipper/imports/api/res.js
- big-dipper/imports/api/utils.js
- big-dipper/imports/startup/server/register-api.js
- big-dipper/package-lock.json
Closes: #XXXX
Big dipper notifications api was added
---
I have...
I have...
> notifications api was added

- .github/workflows/node.js.yml
- app/ante_gate_test.go
- app/export.go
- big-dipper/imports/ui/easel_buy/EaselBuy.jsx
- cmd/pylonsd/cmd/dev.go
- cmd/pylonsd/cmd/gadgets.go
- cmd/pylonsd/cmd/testnet.go
- testutil/cli/cli_test_util.go
- x/pylons/keeper/execute_recipe_history.go
- x/pylons/keeper/grpc_query_list_executions_by_item_test.go
- x/pylons/keeper/grpc_query_payment_info.go
- x/pylons/keeper/grpc_query_redeem_info.go
- x/pylons/keeper/lock.go
- x/pylons/keeper/msg_get_tx_history.go
- x/pylons/keeper/recipe.go
- x/pylons/types/cel_decls.go
- x/pylons/types/expected_keepers.go
- x/pylons/types/item.go
- x/pylons/types/message_apple_iap.go
- x/pylons/types/message_complete_execution_early.go
- x/pylons/types/message_execute_recipe.go
- x/pylons/types/message_google_iap_get_coins.go
- x/pylons/types/message_send_items.go
- x/pylons/types/message_set_item_string.go
- x/pylons/types/message_transfer_cookbook.go
- x/pylons/types/messages_account.go
- x/pylons/types/messages_cookbook.go
- x/pylons/types/messages_recipe.go
- x/pylons/types/validate_common_fields.go
Closes: #XXXX
---
I have...
I have...
> fixed tradePercent value on easelbuy page

- networks/pylons-testnet-3/genesis.json
- pylonsss.bash
State sync script
---
I have...
I have...
> Fix statesync

- x/pylons/keeper/msg_server_recipe_test.go
- x/pylons/keeper/msg_server_trade_test.go
**What is the purpose of the change**
- Update test case for [CreateRecipe](https://github.com/levanhieuhust/pylons/blob/33ce9d94eeef09838052ffd2b44be7a0af497698/x/pylons/keeper/msg_server_recipe.go#L15) function
**Brief Changelog**
- Write all test cases with table-driven test [CreateRecipe](https://github.com/levanhieuhust/pylons/blob/33ce9d94eeef09838052ffd2b44be7a0af497698/x/pylons/keeper/msg_server_recipe.go#L15) function
**Testing and Verifying**
- This change is a trivial rework/code cleanup without any test coverage
**Documentation and Release Note**
- Does this pull request introduces a new feature or user-facing behaviour changes? no
- How is the feature or change documented? not applicable
> Update table-driven testing for msg_server_recipe_test and msg_server_trade_test

- x/pylons/keeper/msg_server_burn_debt_token.go
- x/pylons/keeper/msg_server_burn_debt_token_test.go
- x/pylons/keeper/msg_server_execute_recipe_test.go
- x/pylons/keeper/msg_server_trade.go
- x/pylons/keeper/process_payment_info.go
- x/pylons/keeper/process_payment_info_test.go
Closes: Stripe Payment Issue when purchasing an NFT
In our param space, we have the naming convention issue. Fixed it.
---
I have...
I have...
> fix: moved payment processor to get value from defaults

- big-dipper/client/styles.scss
- big-dipper/imports/ui/easel_buy/EaselBuy.jsx
Closes: #XXXX
---
I have...
I have...
> mobile view image issue resolved

- big-dipper/client/styles.scss
Closes: #XXXX
Fix for big dipper mobile ui buy now button  
---
I have...
I have...
> big-dipper UI for buy now was updated

- easel/android/app/build.gradle
- easel/lib/models/nft.dart
- easel/lib/screens/creator_hub/widgets/draft_list_tile.dart
- easel/lib/screens/creator_hub/widgets/nfts_list_tile.dart
- easel/lib/utils/dependency_injection/dependency_injection_container.dart
- easel/lib/utils/easel_app_theme.dart
- easel/pubspec.yaml
Following issue is resolved in this PR:
1. #832
> Added Grey Placeholders while Thumbnails are loading in Easel

- .gitignore
- big-dipper-backend/.gitignore
- big-dipper/.gitignore
- big-dipper/settings.json
Closes: #XXXX
---
I have...
I have...
> added settings json back

- easel/android/app/json_manipulator.sh
- easel/lib/main.dart
The pipeline will now make easel build as a part of the CI. This is meant to caught build related issues on the easel side.
> Added easel build making script

- wallet/lib/pages/detailed_asset_view/owner_view_view_model.dart
- wallet/lib/pages/purchase_item/purchase_item_view_model.dart
Following issue resolved:
1. #901
> Resolved Liking NFT Bug

- wallet/lib/components/user_image_widget.dart
- wallet/lib/pages/home/home.dart
- wallet/lib/pages/presenting_onboard_page/components/import_from_google_form.dart
- wallet/lib/stores/wallet_store.dart
- wallet/lib/stores/wallet_store_dummy_inventory.dart
- wallet/lib/stores/wallet_store_imp.dart
- wallet/test/mocks/mock_wallet_store.dart
This will solve this issue. 
https://github.com/Pylons-tech/pylons/issues/909 
We now will only require mnemonic to import your account.
> Removed adding username

- x/pylons/types/params.go
Closes: #XXXX
Enables App Check globally
---
I have...
I have...
> fix: app-check is enabled globally

- x/pylons/client/cli/query_cookbook_test.go
- Write table-driven test code 
- Write all cli test cases with table-driven test for `CmdShowCookbook` function
- This change is a trivial rework/code cleanup without any test coverage
- Does this pull request introduces a new feature or user-facing behaviour changes? no 
- How is the feature or change documented? not applicable
---
> table test driven for query cookbook

- big-dipper/imports/ui/easel_buy/EaselBuy.jsx
Closes: #XXXX
---
I have...
I have...
> fix: buy now free issue fixed

- big-dipper/imports/ui/App.jsx
- big-dipper/imports/ui/item_share/ItemShare.jsx
Closes: #XXXX
For item share page nav bar was set to be hidden on mobile view
for item share page item name was udpated
---
I have...
I have...
> fix: nav bar was set to hide on mobile view on item share

- x/pylons/client/cli/query_list_recipes_by_cookbook_test.go
- x/pylons/keeper/pylons_account.go
Closes: #XXXX
---
I have...
I have...
> add query list recipes by cookbook test

- .github/dependabot.yml
enables dependabot for the dart sdk
---
I have...
I have...
> use dependabot for dart sdk

- proto/pylons/pylons/redeem_info.proto
> SUPER SHORT, EASY MERGE: fix semicolon in proto

- easel/lib/repository/repository.dart
- easel/lib/screens/creator_hub/widgets/drafts_more_bottomsheet.dart
- easel/lib/screens/creator_hub/widgets/nfts_grid_view.dart
- easel/lib/utils/constants.dart
- easel/test/extensions/size_extension.dart
- easel/test/mocks/mock_constants.dart
- easel/test/widget/grid_view_draft_list_test.dart
Removing three points from menu affected the 3d ability to publish on wallet.
> Fix three d upload issue

- wallet/lib/services/data_stores/remote_data_store.dart
This should resolve the FCM token issue.
> FCM token hotfix in Pylons

- wallet/lib/ipc/ipc_engine.dart
- wallet/lib/pages/purchase_item/purchase_item_screen.dart
- wallet/lib/pages/purchase_item/purchase_item_view_model.dart
- wallet/lib/pylons_app.dart
- wallet/lib/services/data_stores/remote_data_store.dart
- wallet/lib/services/repository/repository.dart
- wallet/lib/services/third_party_services/analytics_helper.dart
- wallet/lib/utils/route_util.dart
- wallet/test/mocks/mock_analytics_helper.dart
- wallet/test/mocks/mock_repository.dart
The logs contains info recipeid, recipe name, author and price.
> Added ecommerce log when a purchase nft is opened

- easel/lib/screens/preview_screen.dart
- easel/lib/widgets/image_widget.dart
- wallet/lib/pages/detailed_asset_view/widgets/nft_image_asset.dart
Now whatever the user selects he will see the original aspect ratio. He can change it on that page the aspect ratio.
> Restore creater images to their original aspect ratio

- x/pylons/client/cli/tx_transfer_cookbook_test.go
add cli/tx_transfer_cookbook_test, handle errors include: invalid id, cookbook not found, invalid owner
Closes: #XXXX
---
I have...
I have...
> add cli/tx_transfer_cookbook_test

- x/pylons/client/cli/tx_trade_test.go
Add cli/tx_trade_test, handle errors are returned from message.ValidateBasic() and keeper (not include coin-denom aspects)
---
I have...
I have...
> add cli/tx_trade_test

- x/pylons/client/cli/tx_cookbook_test.go
add cli/tx_cookbook_test.go, create and update, handle errors are returned from msg.ValidateBasic() and keeper (not include coin-denom aspects)
Closes: #XXXX
---
I have...
I have...
> add cli/tx_cookbook_test.go

- wallet/lib/pages/home/currency_screen/model/ibc_coins.dart
- wallet/lib/pages/purchase_item/widgets/buy_nft_button.dart
- wallet/lib/pages/purchase_item/widgets/pay_now_dialog.dart
Issue: 
Right now even if the generate stripe call fails. System still hits the chain this was causing double failures logs. 
Resolution: 
If the generate receipt call fails system will throw stripe failure error.
> Solved stripe failure twice logging issue

- wallet/lib/utils/constants.dart
Changed pylon price to 0.10 mention in https://github.com/Pylons-tech/pylons/issues/1120
> Fix-1120:  changed pylonToUsdConstant to 0.10 from 0.01

- wallet/ios/Podfile
- wallet/lib/pages/detailed_asset_view/widgets/nft_3d_asset.dart
- wallet/lib/pages/purchase_item/purchase_item_screen.dart
This PR solves the issue of White Background in case of 3D Model
> Fixed NFT 3D model white background issue

- wallet/lib/pages/detailed_asset_view/widgets/nft_3d_asset.dart
Issue mentioned in https://github.com/Pylons-tech/pylons/issues/1225#issuecomment-1285003213
> Fixed white line at bottom of 3D Model

- wallet/android/app/build.gradle
- wallet/android/app/src/main/kotlin/tech/pylons/wallet/MainActivity.kt
- wallet/ios/Podfile
- wallet/ios/Runner/AppDelegate.swift
- wallet/lib/main_prod.dart
- wallet/lib/utils/constants.dart
Fix Firebase AppCheck issue, Firebase was not providing AppCheck token in debug mode when we use `AndroidProvider.playIntegrity` 
This PR resolve issue https://github.com/Pylons-tech/pylons/issues/1311
> Fix Firebase AppCheck issue

- app/upgrades/v4/upgrades.go
Closes: #XXXX
---
I have...
I have...
> fixed bedrock distrubution

- wallet/lib/pages/routing_page/splash_screen.dart
Issue of transition mentioned in https://github.com/Pylons-tech/pylons/issues/1342#issuecomment-1318974787
> Enhance shadow below pylons images & added fade transition

- easel/lib/screens/creator_hub/creator_hub_screen.dart
- easel/lib/screens/creator_hub/widgets/nfts_list_tile.dart
- easel/lib/utils/extension_util.dart
- easel/test/mocks/mock_constants.dart
- easel/test/widget/gridview_banner_for_draft_published_test.dart
- easel/test/widget/nfts_list_tile_test.dart
This PR solves the issue mentioned in https://github.com/Pylons-tech/pylons/issues/1403 & https://github.com/Pylons-tech/pylons/issues/1401
> Fixed price banner for both list and grid view in Easel.

- wallet/lib/main_prod.dart
Remove `SafetyNet` Provider as it is going to deprecated soon
> Remove safetyNet Provider

- dart_sdk/lib/src/generated/pylons/execution.pb.dart
- dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart
- wallet/lib/ipc/ipc_engine.dart
- wallet/lib/main_prod.dart
- wallet/lib/model/nft.dart
- wallet/lib/pages/home/collection_screen/collection_view_model.dart
- wallet/lib/stores/wallet_store_imp.dart
I have cherry picked the code from the afti branch regarding
1) Ignoring the non easel items. 
2) Execution fix from the wallet.
> Cherry picked code from afti PR

- app/upgrades/v5/constants.go
Closes: #XXXX
---
I have...
I have...
> updated upgrade Name

- app/upgrades/v5/constants.go
Closes: #XXXX
---
I have...
I have...
> updated proposal

- wallet/lib/pages/routing_page/splash_screen.dart
- wallet/lib/utils/image_util.dart
Remove layer below `Pylons` and smoother animation mentioned in https://github.com/Pylons-tech/pylons/issues/1342
> Remove BG below layer and smoother animation

- networks/pylons-mainnet-1/README.md
Updated chain id from pylons-testnet-3 to pylons-mainnet-1 by oxes
Closes: #XXXX
---
I have...
I have...
> Updated chain id

- networks/pylons-mainnet-1/README.md
Closes: #XXXX
---
I have...
I have...
> gentx with ubedrock

- networks/pylons-mainnet-1/README.md
Closes: #XXXX
---
I have...
I have...
> updated readme

- networks/pylons-mainnet-1/README.md
Closes: #XXXX
---
I have...
I have...
> match shas and more rock

- app/upgrades/v4/upgrades_test.go
- app/upgrades/v6/upgrades.go
- x/pylons/client/cli/query_list_trades_by_creator_test.go
- x/pylons/client/cli/tx_cookbook_test.go
- x/pylons/types/messages_account_test.go
Closes: #XXXX
---
I have...
I have...
> linter fixed

- networks/pylons-mainnet-1/README.md
Closes: #XXXX
---
I have...
I have...
> Add seed node to mainnet

- x/pylons/types/default_cel.go
- x/pylons/types/messages_recipe.go
- x/pylons/types/messages_recipe_test.go
- x/pylons/types/recipe.go
- x/pylons/types/recipe_test.go
Closes: #XXXX
---
I have...
I have...
> cel variables fixed

- wallet/lib/main_development.dart
- wallet/lib/services/data_stores/remote_data_store.dart
- wallet/lib/services/third_party_services/remote_config_service/remote_config_service.dart
- wallet/lib/utils/dependency_injection/dependency_injection.dart
1) Added prod and dev flavors for the wallet. 
2) Added timeout for each http call.
> Flavors added

- wallet/lib/model/nft.dart
- wallet/lib/pages/purchase_item/widgets/pay_now_dialog.dart
- wallet/lib/providers/items_provider.dart
- wallet/lib/providers/recipes_provider.dart
- wallet/lib/services/data_stores/local_data_store.dart
- wallet/lib/services/data_stores/remote_data_store.dart
- wallet/lib/services/repository/repository.dart
- wallet/lib/services/third_party_services/remote_config_service/remote_config_service.dart
- wallet/lib/utils/base_env.dart
- wallet/lib/utils/constants.dart
- wallet/lib/utils/enums.dart
- wallet/test/mocks/mock_constants.dart
- wallet/test/mocks/mock_local_data_source.dart
- wallet/test/mocks/mock_repository.dart
1) Added the cache feature for Purchases. 
2) Added the cache feature for cookbooks. 
3) Added the cache feature for Creations.
> Added the cache feature in the app

- wallet/lib/model/common.dart
- wallet/lib/pages/detailed_asset_view/owner_view.dart
- wallet/lib/pages/detailed_asset_view/owner_view_view_model.dart
- wallet/lib/pages/detailed_asset_view/widgets/toggle_button.dart
- wallet/lib/services/data_stores/remote_data_store.dart
- wallet/lib/services/repository/repository.dart
- wallet/test/mocks/mock_repository.dart
1) Added the enable disable feature for the recipe. 
2) Wrapped common fields into model classes. i-e Address, RecipeId and cookbookId.
3) Updated remote datasource with model classes.
> Added the enable disable recipe feature

- dart_sdk/example/test/widget_test.dart
- dart_sdk/lib/src/features/ipc/base/ipc_handler.dart
- dart_sdk/lib/src/features/ipc/handlers/execute_recipe_handler.dart
- dart_sdk/lib/src/features/ipc/handlers/get_cookbooks_handler.dart
- dart_sdk/lib/src/features/ipc/handlers/get_profile_handler.dart
- dart_sdk/lib/src/features/ipc/handlers/get_recipe_handler.dart
- dart_sdk/lib/src/features/ipc/handlers/get_recipes_handler.dart
- dart_sdk/lib/src/features/models/sdk_ipc_response.dart
- dart_sdk/lib/src/pylons_wallet/pylons_wallet_impl.dart
- dart_sdk/test/src/features/ipc/handlers/get_recipes_handler_test.dart
- testapp-flutter/pubspec.lock
- wallet/lib/ipc/models/sdk_ipc_response.dart
- wallet/lib/services/repository/repository.dart
- wallet/lib/services/third_party_services/stripe_handler.dart
1) Added the returned response in case of error.
2) Added the Generalization in the Handlers.
> Added the error in the returned response.

- buy-now/Dockerfile
Closes: #XXXX
---
I have...
I have...
> updated docker file

- wallet/lib/components/loading.dart
- wallet/lib/ipc/handler/handlers/create_cookbook_handler.dart
- wallet/lib/ipc/handler/handlers/create_recipe_handler.dart
- wallet/lib/ipc/handler/handlers/get_profile_handler.dart
- wallet/lib/model/wallet_creation_model.dart
- wallet/lib/pages/presenting_onboard_page/screens/accept_policy_screen.dart
- wallet/lib/pages/presenting_onboard_page/viewmodel/accept_policy_viewmodel.dart
- wallet/lib/pages/purchase_item/purchase_item_screen.dart
- wallet/lib/pages/purchase_item/purchase_item_view_model.dart
- wallet/lib/services/data_stores/remote_data_store.dart
- wallet/lib/stores/wallet_store.dart
- wallet/lib/stores/wallet_store_imp.dart
- wallet/lib/utils/clipper_utils.dart
- wallet/lib/utils/dependency_injection/dependency_injection.dart
- wallet/test/mocks/mock_wallet_store.dart
- wallet/test/widget_testing/pages/accept_policy/accept_policy_screen_test.dart
1) Creating account on Accept policy flow.
2) Directed to buy now coins from buy now flow.
> Creating account on nft purchase flow.

- easel/lib/screens/choose_format_screen.dart
- easel/lib/screens/custom_widgets/step_labels.dart
- easel/lib/screens/describe_screen.dart
- easel/lib/screens/preview_nft/nft_image_screen.dart
- easel/lib/screens/preview_screen.dart
- easel/lib/screens/price_screen.dart
- easel/lib/screens/welcome_screen/widgets/show_something_wrong_dialog.dart
- easel/lib/screens/welcome_screen/widgets/show_wallet_install_dialog.dart
- easel/lib/utils/easel_app_theme.dart
- easel/lib/widgets/pylons_button.dart
- wallet/analysis_options.yaml
- wallet/lib/components/no_internet.dart
- wallet/lib/components/pylons_app_theme.dart
- wallet/lib/ipc/local_server.dart
- wallet/lib/ipc/widgets/sdk_approval_dialog.dart
- wallet/lib/pages/detailed_asset_view/owner_view.dart
- wallet/lib/pages/detailed_asset_view/widgets/nft_image_asset.dart
- wallet/lib/pages/home/currency_screen/widgets/balance_ibc_coins.dart
- wallet/lib/pages/purchase_item/purchase_item_screen.dart
- wallet/lib/pages/routing_page/update_app.dart
- wallet/lib/pages/transaction_failure_manager/local_transactions_screen.dart
- wallet/lib/services/data_stores/remote_data_store.dart
- wallet/lib/utils/extension.dart
1) Updated the flutter version from 3.3.7 to 3.7.0.
> Update flutter to 3.7.0 in for CI pipeline

- flame-demo/README.md
- flame-demo/android/app/build.gradle
- flame-demo/lib/doohickey.dart
- flame-demo/lib/game.dart
- flame-demo/lib/hud.dart
- flame-demo/lib/main.dart
- flame-demo/lib/pylons_component.dart
- flame-demo/lib/recipe.dart
Fixes the copied README (and a package name issue!) and implements interactive recipe execution.
In this case, it's just running the BlockSlayer get-character recipe when you tap the screen after a profile has been retrieved, which obviously isn't super showy or useful, but it demonstrates how you can write something that executes a recipe from within the update loop and then runs a callback on the returned data within the update loop once the recipe finishes.
---
I have...
I have...
> Interactive recipe execution + readme

- app/app.go
- app/fix_bonded_tokens_pool.go
- app/fix_bonded_tokens_pool_test.go
As a follow-up to Pylons-tech/pylons#1852, this relocates the code to it's own files and adds a test.
> Improving the fix and adding a test

- docs/Developer-CLI-Tutorial.md
- docs/RECIPE_WALKTHROUGH.md
> Fix: typos

- testapp-flutter/lib/main.dart
- wallet/macos/Flutter/GeneratedPluginRegistrant.swift
- wallet/pkgs/transaction_signing_gateway/pubspec.yaml
- wallet/pubspec.yaml
- wallet/test/unit_testing/services/data_stores/remote_data_store_test.mocks.dart
1. Upgraded code to latest flutter 3.7.7 
2. Upgraded flutter secure storage. 
3. Upgraded home widget.
> Updated the code to flutter 3.7.7 and upgraded few packages

- wallet/lib/pages/owner_purchase_view_common/qr_code_screen.dart
Closes: #XXXX
---
I have...
I have...
> fix: qr code scanning does not work

- easel/test/extensions/size_extensions.dart
fix error in the tests in easel
> fix error in the tests in easel

- evently/lib/evently_provider.dart
- evently/lib/main.dart
- evently/lib/models/events.dart
fixes the constraint of having event length > 10 and adds event creator's name to the recipe name
> fix the event length issue

- easel/pubspec.yaml
fix deprecated error in detectable_text_field
> fix deprecated error in detectable_text_field

- evently/android/app/build.gradle
- evently/pubspec.lock
Description
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file 'C:\Users\ADMIN\Documents\GitHub\pylons\evently\android\app\keystore.jks' not found for signing config 'debug'.
also there was a error in gradle.build 
I have...
I have...
> Rearranged the configues inside Build.gradle to fix error

- wallet/ios/Flutter/AppFrameworkInfo.plist
- wallet/ios/Runner.xcodeproj/project.pbxproj
- wallet/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- wallet/lib/main_prod.dart
- wallet/lib/pages/image_picker.dart
- wallet/lib/pages/stripe_screen.dart
- wallet/pubspec.yaml
Closes: #XXXX
---
I have...
I have...
> fix a few issues that happen due to library upgrades

- wallet/ios/Runner.xcodeproj/project.pbxproj
Closes: #XXXX
---
I have...
I have...
> version bump required in deployment target due to flutter upgrade

- buy-now/Dockerfile
updated docker file to use node.js version 18 instead of 16 because of build error on cloud run
I have...
I have...
> updated docker file to support node 18

- .github/workflows/flutter.yml
- easel/android/app/build.gradle
- easel/lib/env.dart
created a mock env.dart with mock apikey
I have...
I have...
> Mock api key for easel
